# Create Dev Folder Structure
# Creates organized development folders at C:\Dev

param(
    [string]$BasePath = "C:\Dev",
    [string]$LogFile = "$env:ProgramData\SecureSetupWizard\install.log"
)

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] $Message"
    Write-Host $logMessage
    if (Test-Path $LogFile) {
        Add-Content -Path $LogFile -Value $logMessage
    }
}

Write-Log "Creating development folder structure at: $BasePath"

$folders = @(
    $BasePath,
    "$BasePath\projects",
    "$BasePath\bots",
    "$BasePath\security",
    "$BasePath\labs",
    "$BasePath\scripts",
    "$BasePath\notes"
)

foreach ($folder in $folders) {
    try {
        if (-not (Test-Path $folder)) {
            New-Item -ItemType Directory -Path $folder -Force | Out-Null
            Write-Log "  Created: $folder"
        } else {
            Write-Log "  Already exists: $folder"
        }
    } catch {
        Write-Log "  ERROR creating $folder : $_"
    }
}

# Create README file
$readmePath = "$BasePath\README.md"
$readmeContent = @"
# Development Environment

Created by Secure Setup Wizard on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Folder Structure

- **projects/** - General development projects
- **bots/** - Discord bots and automation scripts  
- **security/** - Cybersecurity tools and configurations
- **labs/** - Virtual machine configs and lab environments
- **scripts/** - Utility scripts and automation
- **notes/** - Documentation and learning notes

## Security Reminder

Always conduct security testing in isolated virtual machines.
Never test on systems you do not own or have explicit permission to test.

## Next Steps

1. Configure Git with your identity:
   ```
   git config --global user.name "Your Name"
   git config --global user.email "your.email@example.com"
   ```

2. Set up your first project in the projects/ folder

3. Explore the installed tools in your Start Menu

4. Check the installation log for any warnings

Generated by Secure Setup Wizard
"@

try {
    $readmeContent | Out-File -FilePath $readmePath -Encoding UTF8 -Force
    Write-Log "  Created: $readmePath"
} catch {
    Write-Log "  ERROR creating README: $_"
}

Write-Log "Folder structure creation complete"
